fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        app:
            finder: ~
            settings:
                index:
                    analysis:
                        analyzer:
                            name_analyzer:
                                type: custom
                                tokenizer: standard
                                filter: [standard, lowercase, asciifolding, elision]
            types:
                part:
                    properties:
                        name_suggest:
                            type: completion
                            analyzer: name_analyzer
                            search_analyzer: name_analyzer
                        id:
                            type: keyword
                        name:
                            type: keyword
                    persistence:
                        driver: orm
                        model: App\Entity\Parts\Part
                        provider: ~
                        listener: ~
                        finder: ~