#fos_elastica:
#    clients:
#        default: { host: localhost, port: 9200 }
#    indexes:
#        app:
#            finder: ~
#            client: default
#            settings:
#                index:
#                    analysis:
#                        analyzer:
#                            custom_search_analyzer:
#                                type: custom
#                                tokenizer: standard
#                                filter   : [standard, lowercase, asciifolding]
#                            custom_index_analyzer:
#                                type: custom
#                                tokenizer: standard
#                                filter   : [standard, lowercase, asciifolding, custom_filter]
#                        filter:
#                            custom_filter:
#                                type: edgeNGram
#                                side: front
#                                min_gram: 1
#                                max_gram: 20
#            types:
#                part:
#                    properties:
#                        name: { search_analyzer: custom_search_analyzer, analyzer: custom_index_analyzer, type: text }
#                    persistence:
#                        driver: orm
#                        model: App\Entity\Parts\Part
#                        provider: ~
#                        finder: ~