fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        app:
            types:
                part:
                    properties:
                        name: ~
                    persistence:
                        driver: orm
                        model: App\Entity\Parts\Part
                        finder: ~
                        provider: ~
                        listener: ~