vich_uploader:
    db_driver: orm
    #    storage: gaufrette

    mappings:
        avatars:
            uri_prefix: /avatars
            upload_destination: '%avatars%'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true