vich_uploader:
    db_driver: orm

    mappings:
        avatar_image:
            uri_prefix: /images/avatar
            upload_destination: '%kernel.project_dir%/public/images/avatar'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        logotype_image:
            uri_prefix: /images/logotype
            upload_destination: '%kernel.project_dir%/public/images/logotype'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
