liip_imagine:
    loaders:
        default:
            filesystem:
                data_root:
                    - "%images%"
    resolvers:
        profile_photos:
            web_path: ~
    default_image: /build/images/empty.jpg
    filter_sets:
        cache: ~
        original_thumb:
            cache: profile_photos
            quality: 100
        small_thumb:
            cache: profile_photos
            quality: 100
            filters:
                thumbnail: { size: [220, 165], mode: inset }
                background : { size : [224, 169], position : center, color : '#000000' }
        min_thumb:
            cache: profile_photos
            quality: 100
            filters:
                thumbnail: { size: [120, 90], mode: inset }
                background : { size : [124, 94], position : center, color : '#000000' }
        medium_thumb:
            cache: profile_photos
            quality: 100
            filters:
                thumbnail: { size: [360, 270], mode: inset }
                background : { size : [364, 274], position : center, color : '#000000' }