<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20180813043437 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA client');
        $this->addSql('CREATE SCHEMA drives');
        $this->addSql('CREATE SCHEMA parts');
        $this->addSql('CREATE SCHEMA region');
        $this->addSql('CREATE SCHEMA tyres');
        $this->addSql('CREATE SEQUENCE users_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE client.company_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE client.email_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE client.news_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE client.phone_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE client.price_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE client.section_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE drives.brand_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE drives.drive_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE drives.model_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE parts.brand_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE parts.carcase_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE parts.engine_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE parts.model_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE parts.oem_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE parts.part_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE region.city_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE region.county_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE region.region_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tyres.brand_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tyres.model_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tyres.seasonality_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tyres.thorn_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tyres.tyre_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE users (id INT NOT NULL, city_id INT DEFAULT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled BOOLEAN NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, roles TEXT NOT NULL, first_name VARCHAR(255) NOT NULL, phone VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E992FC23A8 ON users (username_canonical)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9A0D96FBF ON users (email_canonical)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9C05FB297 ON users (confirmation_token)');
        $this->addSql('CREATE INDEX IDX_1483A5E98BAC62AF ON users (city_id)');
        $this->addSql('COMMENT ON COLUMN users.roles IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE client.company (id INT NOT NULL, city_id INT DEFAULT NULL, user_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, preview TEXT NOT NULL, bank TEXT NOT NULL, syte VARCHAR(255) NOT NULL, logotype VARCHAR(255) DEFAULT NULL, address TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7D78DC3C8BAC62AF ON client.company (city_id)');
        $this->addSql('CREATE INDEX IDX_7D78DC3CA76ED395 ON client.company (user_id)');
        $this->addSql('CREATE TABLE client.company_sections (company_id INT NOT NULL, section_id INT NOT NULL, PRIMARY KEY(company_id, section_id))');
        $this->addSql('CREATE INDEX IDX_F4DAD63E979B1AD6 ON client.company_sections (company_id)');
        $this->addSql('CREATE INDEX IDX_F4DAD63ED823E37A ON client.company_sections (section_id)');
        $this->addSql('CREATE TABLE client.email (id INT NOT NULL, company_id INT DEFAULT NULL, address VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_84813EA7979B1AD6 ON client.email (company_id)');
        $this->addSql('CREATE TABLE client.news (id INT NOT NULL, name VARCHAR(255) NOT NULL, picture JSON NOT NULL, slag VARCHAR(255) NOT NULL, display INT NOT NULL, massage VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE client.phone (id INT NOT NULL, company_id INT DEFAULT NULL, number VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_275CD50E979B1AD6 ON client.phone (company_id)');
        $this->addSql('CREATE TABLE client.price (id INT NOT NULL, company_id INT DEFAULT NULL, path VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A9DB600A979B1AD6 ON client.price (company_id)');
        $this->addSql('CREATE TABLE client.section (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE drives.brand (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE drives.drive (id INT NOT NULL, brands_id INT DEFAULT NULL, models_id INT DEFAULT NULL, diameter DOUBLE PRECISION NOT NULL, departure DOUBLE PRECISION NOT NULL, drilling VARCHAR(255) NOT NULL, width DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8E96ED72E9EEC0C7 ON drives.drive (brands_id)');
        $this->addSql('CREATE INDEX IDX_8E96ED72D966BF49 ON drives.drive (models_id)');
        $this->addSql('CREATE TABLE drives.model (id INT NOT NULL, brands_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_311E6A24E9EEC0C7 ON drives.model (brands_id)');
        $this->addSql('CREATE TABLE parts.brand (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE parts.carcase (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE parts.models_carcases (carcase_id INT NOT NULL, model_id INT NOT NULL, PRIMARY KEY(carcase_id, model_id))');
        $this->addSql('CREATE INDEX IDX_F26C23CB2E4BDF84 ON parts.models_carcases (carcase_id)');
        $this->addSql('CREATE INDEX IDX_F26C23CB7975B7E7 ON parts.models_carcases (model_id)');
        $this->addSql('CREATE TABLE parts.engine (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE parts.model (id INT NOT NULL, brand_id INT DEFAULT NULL, rank INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AC5ED35C44F5D008 ON parts.model (brand_id)');
        $this->addSql('CREATE TABLE parts.oem (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE parts.part (id INT NOT NULL, brand_id INT DEFAULT NULL, model_id INT DEFAULT NULL, city_id INT DEFAULT NULL, company_id INT DEFAULT NULL, name TEXT NOT NULL, hash VARCHAR(255) NOT NULL, price NUMERIC(10, 0) NOT NULL, slug VARCHAR(255) NOT NULL, picture JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_33855B0C44F5D008 ON parts.part (brand_id)');
        $this->addSql('CREATE INDEX IDX_33855B0C7975B7E7 ON parts.part (model_id)');
        $this->addSql('CREATE INDEX IDX_33855B0C8BAC62AF ON parts.part (city_id)');
        $this->addSql('CREATE INDEX IDX_33855B0C979B1AD6 ON parts.part (company_id)');
        $this->addSql('CREATE TABLE parts.parts_carcases (part_id INT NOT NULL, carcase_id INT NOT NULL, PRIMARY KEY(part_id, carcase_id))');
        $this->addSql('CREATE INDEX IDX_D4026B4B4CE34BEC ON parts.parts_carcases (part_id)');
        $this->addSql('CREATE INDEX IDX_D4026B4B2E4BDF84 ON parts.parts_carcases (carcase_id)');
        $this->addSql('CREATE TABLE parts.parts_engines (part_id INT NOT NULL, engine_id INT NOT NULL, PRIMARY KEY(part_id, engine_id))');
        $this->addSql('CREATE INDEX IDX_1AE1F44CE34BEC ON parts.parts_engines (part_id)');
        $this->addSql('CREATE INDEX IDX_1AE1F4E78C9C0A ON parts.parts_engines (engine_id)');
        $this->addSql('CREATE TABLE parts.parts_oems (part_id INT NOT NULL, oem_id INT NOT NULL, PRIMARY KEY(part_id, oem_id))');
        $this->addSql('CREATE INDEX IDX_769A7E454CE34BEC ON parts.parts_oems (part_id)');
        $this->addSql('CREATE INDEX IDX_769A7E4549FED7ED ON parts.parts_oems (oem_id)');
        $this->addSql('CREATE TABLE region.city (id INT NOT NULL, region_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, coordinate VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_304FDC7C98260155 ON region.city (region_id)');
        $this->addSql('CREATE TABLE region.county (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE region.region (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE tyres.brand (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE tyres.model (id INT NOT NULL, brand_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_98EF507744F5D008 ON tyres.model (brand_id)');
        $this->addSql('CREATE TABLE tyres.seasonality (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE tyres.thorn (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE tyres.tyre (id INT NOT NULL, thorn_id INT DEFAULT NULL, seasonality_id INT DEFAULT NULL, brand_id INT DEFAULT NULL, model_id INT DEFAULT NULL, city_id INT DEFAULT NULL, company_id INT DEFAULT NULL, width INT NOT NULL, height INT NOT NULL, diameter DOUBLE PRECISION NOT NULL, quantity INT NOT NULL, hash VARCHAR(255) NOT NULL, price NUMERIC(10, 0) NOT NULL, picture JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1B38C908CD28D0B3 ON tyres.tyre (thorn_id)');
        $this->addSql('CREATE INDEX IDX_1B38C908C8DAFA57 ON tyres.tyre (seasonality_id)');
        $this->addSql('CREATE INDEX IDX_1B38C90844F5D008 ON tyres.tyre (brand_id)');
        $this->addSql('CREATE INDEX IDX_1B38C9087975B7E7 ON tyres.tyre (model_id)');
        $this->addSql('CREATE INDEX IDX_1B38C9088BAC62AF ON tyres.tyre (city_id)');
        $this->addSql('CREATE INDEX IDX_1B38C908979B1AD6 ON tyres.tyre (company_id)');
        $this->addSql('CREATE INDEX width_idx ON tyres.tyre (width)');
        $this->addSql('CREATE INDEX height_idx ON tyres.tyre (height)');
        $this->addSql('CREATE INDEX diameter_idx ON tyres.tyre (diameter)');
        $this->addSql('CREATE INDEX quantity_idx ON tyres.tyre (quantity)');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E98BAC62AF FOREIGN KEY (city_id) REFERENCES region.city (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE client.company ADD CONSTRAINT FK_7D78DC3C8BAC62AF FOREIGN KEY (city_id) REFERENCES region.city (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE client.company ADD CONSTRAINT FK_7D78DC3CA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE client.company_sections ADD CONSTRAINT FK_F4DAD63E979B1AD6 FOREIGN KEY (company_id) REFERENCES client.company (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE client.company_sections ADD CONSTRAINT FK_F4DAD63ED823E37A FOREIGN KEY (section_id) REFERENCES client.section (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE client.email ADD CONSTRAINT FK_84813EA7979B1AD6 FOREIGN KEY (company_id) REFERENCES client.company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE client.phone ADD CONSTRAINT FK_275CD50E979B1AD6 FOREIGN KEY (company_id) REFERENCES client.company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE client.price ADD CONSTRAINT FK_A9DB600A979B1AD6 FOREIGN KEY (company_id) REFERENCES client.company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE drives.drive ADD CONSTRAINT FK_8E96ED72E9EEC0C7 FOREIGN KEY (brands_id) REFERENCES drives.brand (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE drives.drive ADD CONSTRAINT FK_8E96ED72D966BF49 FOREIGN KEY (models_id) REFERENCES drives.brand (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE drives.model ADD CONSTRAINT FK_311E6A24E9EEC0C7 FOREIGN KEY (brands_id) REFERENCES drives.brand (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parts.models_carcases ADD CONSTRAINT FK_F26C23CB2E4BDF84 FOREIGN KEY (carcase_id) REFERENCES parts.carcase (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parts.models_carcases ADD CONSTRAINT FK_F26C23CB7975B7E7 FOREIGN KEY (model_id) REFERENCES parts.model (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parts.model ADD CONSTRAINT FK_AC5ED35C44F5D008 FOREIGN KEY (brand_id) REFERENCES parts.brand (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parts.part ADD CONSTRAINT FK_33855B0C44F5D008 FOREIGN KEY (brand_id) REFERENCES parts.brand (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parts.part ADD CONSTRAINT FK_33855B0C7975B7E7 FOREIGN KEY (model_id) REFERENCES parts.model (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parts.part ADD CONSTRAINT FK_33855B0C8BAC62AF FOREIGN KEY (city_id) REFERENCES region.city (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parts.part ADD CONSTRAINT FK_33855B0C979B1AD6 FOREIGN KEY (company_id) REFERENCES client.company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parts.parts_carcases ADD CONSTRAINT FK_D4026B4B4CE34BEC FOREIGN KEY (part_id) REFERENCES parts.part (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parts.parts_carcases ADD CONSTRAINT FK_D4026B4B2E4BDF84 FOREIGN KEY (carcase_id) REFERENCES parts.carcase (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parts.parts_engines ADD CONSTRAINT FK_1AE1F44CE34BEC FOREIGN KEY (part_id) REFERENCES parts.part (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parts.parts_engines ADD CONSTRAINT FK_1AE1F4E78C9C0A FOREIGN KEY (engine_id) REFERENCES parts.engine (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parts.parts_oems ADD CONSTRAINT FK_769A7E454CE34BEC FOREIGN KEY (part_id) REFERENCES parts.part (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parts.parts_oems ADD CONSTRAINT FK_769A7E4549FED7ED FOREIGN KEY (oem_id) REFERENCES parts.oem (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE region.city ADD CONSTRAINT FK_304FDC7C98260155 FOREIGN KEY (region_id) REFERENCES region.region (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tyres.model ADD CONSTRAINT FK_98EF507744F5D008 FOREIGN KEY (brand_id) REFERENCES tyres.brand (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tyres.tyre ADD CONSTRAINT FK_1B38C908CD28D0B3 FOREIGN KEY (thorn_id) REFERENCES tyres.thorn (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tyres.tyre ADD CONSTRAINT FK_1B38C908C8DAFA57 FOREIGN KEY (seasonality_id) REFERENCES tyres.seasonality (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tyres.tyre ADD CONSTRAINT FK_1B38C90844F5D008 FOREIGN KEY (brand_id) REFERENCES tyres.brand (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tyres.tyre ADD CONSTRAINT FK_1B38C9087975B7E7 FOREIGN KEY (model_id) REFERENCES tyres.model (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tyres.tyre ADD CONSTRAINT FK_1B38C9088BAC62AF FOREIGN KEY (city_id) REFERENCES region.city (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tyres.tyre ADD CONSTRAINT FK_1B38C908979B1AD6 FOREIGN KEY (company_id) REFERENCES client.company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE client.company DROP CONSTRAINT FK_7D78DC3CA76ED395');
        $this->addSql('ALTER TABLE client.company_sections DROP CONSTRAINT FK_F4DAD63E979B1AD6');
        $this->addSql('ALTER TABLE client.email DROP CONSTRAINT FK_84813EA7979B1AD6');
        $this->addSql('ALTER TABLE client.phone DROP CONSTRAINT FK_275CD50E979B1AD6');
        $this->addSql('ALTER TABLE client.price DROP CONSTRAINT FK_A9DB600A979B1AD6');
        $this->addSql('ALTER TABLE parts.part DROP CONSTRAINT FK_33855B0C979B1AD6');
        $this->addSql('ALTER TABLE tyres.tyre DROP CONSTRAINT FK_1B38C908979B1AD6');
        $this->addSql('ALTER TABLE client.company_sections DROP CONSTRAINT FK_F4DAD63ED823E37A');
        $this->addSql('ALTER TABLE drives.drive DROP CONSTRAINT FK_8E96ED72E9EEC0C7');
        $this->addSql('ALTER TABLE drives.drive DROP CONSTRAINT FK_8E96ED72D966BF49');
        $this->addSql('ALTER TABLE drives.model DROP CONSTRAINT FK_311E6A24E9EEC0C7');
        $this->addSql('ALTER TABLE parts.model DROP CONSTRAINT FK_AC5ED35C44F5D008');
        $this->addSql('ALTER TABLE parts.part DROP CONSTRAINT FK_33855B0C44F5D008');
        $this->addSql('ALTER TABLE parts.models_carcases DROP CONSTRAINT FK_F26C23CB2E4BDF84');
        $this->addSql('ALTER TABLE parts.parts_carcases DROP CONSTRAINT FK_D4026B4B2E4BDF84');
        $this->addSql('ALTER TABLE parts.parts_engines DROP CONSTRAINT FK_1AE1F4E78C9C0A');
        $this->addSql('ALTER TABLE parts.models_carcases DROP CONSTRAINT FK_F26C23CB7975B7E7');
        $this->addSql('ALTER TABLE parts.part DROP CONSTRAINT FK_33855B0C7975B7E7');
        $this->addSql('ALTER TABLE parts.parts_oems DROP CONSTRAINT FK_769A7E4549FED7ED');
        $this->addSql('ALTER TABLE parts.parts_carcases DROP CONSTRAINT FK_D4026B4B4CE34BEC');
        $this->addSql('ALTER TABLE parts.parts_engines DROP CONSTRAINT FK_1AE1F44CE34BEC');
        $this->addSql('ALTER TABLE parts.parts_oems DROP CONSTRAINT FK_769A7E454CE34BEC');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E98BAC62AF');
        $this->addSql('ALTER TABLE client.company DROP CONSTRAINT FK_7D78DC3C8BAC62AF');
        $this->addSql('ALTER TABLE parts.part DROP CONSTRAINT FK_33855B0C8BAC62AF');
        $this->addSql('ALTER TABLE tyres.tyre DROP CONSTRAINT FK_1B38C9088BAC62AF');
        $this->addSql('ALTER TABLE region.city DROP CONSTRAINT FK_304FDC7C98260155');
        $this->addSql('ALTER TABLE tyres.model DROP CONSTRAINT FK_98EF507744F5D008');
        $this->addSql('ALTER TABLE tyres.tyre DROP CONSTRAINT FK_1B38C90844F5D008');
        $this->addSql('ALTER TABLE tyres.tyre DROP CONSTRAINT FK_1B38C9087975B7E7');
        $this->addSql('ALTER TABLE tyres.tyre DROP CONSTRAINT FK_1B38C908C8DAFA57');
        $this->addSql('ALTER TABLE tyres.tyre DROP CONSTRAINT FK_1B38C908CD28D0B3');
        $this->addSql('DROP SEQUENCE users_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE client.company_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE client.email_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE client.news_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE client.phone_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE client.price_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE client.section_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE drives.brand_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE drives.drive_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE drives.model_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE parts.brand_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE parts.carcase_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE parts.engine_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE parts.model_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE parts.oem_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE parts.part_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE region.city_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE region.county_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE region.region_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tyres.brand_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tyres.model_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tyres.seasonality_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tyres.thorn_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tyres.tyre_id_seq CASCADE');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE client.company');
        $this->addSql('DROP TABLE client.company_sections');
        $this->addSql('DROP TABLE client.email');
        $this->addSql('DROP TABLE client.news');
        $this->addSql('DROP TABLE client.phone');
        $this->addSql('DROP TABLE client.price');
        $this->addSql('DROP TABLE client.section');
        $this->addSql('DROP TABLE drives.brand');
        $this->addSql('DROP TABLE drives.drive');
        $this->addSql('DROP TABLE drives.model');
        $this->addSql('DROP TABLE parts.brand');
        $this->addSql('DROP TABLE parts.carcase');
        $this->addSql('DROP TABLE parts.models_carcases');
        $this->addSql('DROP TABLE parts.engine');
        $this->addSql('DROP TABLE parts.model');
        $this->addSql('DROP TABLE parts.oem');
        $this->addSql('DROP TABLE parts.part');
        $this->addSql('DROP TABLE parts.parts_carcases');
        $this->addSql('DROP TABLE parts.parts_engines');
        $this->addSql('DROP TABLE parts.parts_oems');
        $this->addSql('DROP TABLE region.city');
        $this->addSql('DROP TABLE region.county');
        $this->addSql('DROP TABLE region.region');
        $this->addSql('DROP TABLE tyres.brand');
        $this->addSql('DROP TABLE tyres.model');
        $this->addSql('DROP TABLE tyres.seasonality');
        $this->addSql('DROP TABLE tyres.thorn');
        $this->addSql('DROP TABLE tyres.tyre');
    }
}
